const result = [
  {
    player_one: "Jones, Marc",
    player_two: "O'Sullivan, Mark",
    g1s: 62,
    g2s: 69,
    g3s: 0,
    g4s: 66,
    g5s: 0,
    g6s: 65,
  },
  {
    player_one: "Linnane, Michael M",
    player_two: "Grieves, Mike",
    g1s: 62,
    g2s: 0,
    g3s: 70,
    g4s: 65,
    g5s: 67,
    g6s: 0,
  },
  {
    player_one: "Tristram, Corey",
    player_two: "Miles, Mike J",
    g1s: 64,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "King, William John",
    player_two: "Bromham, Derek J",
    g1s: 66,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Williams, Dafydd",
    player_two: "Lukes, Ben",
    g1s: 66,
    g2s: 0,
    g3s: 65,
    g4s: 61,
    g5s: 68,
    g6s: 0,
  },
  {
    player_one: "Maimone, Nigel P.",
    player_two: "Barriscale, Phil C.",
    g1s: 67,
    g2s: 0,
    g3s: 69,
    g4s: 65,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Hughes, Steven",
    player_two: "Dacey, Kevin",
    g1s: 67,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Price, Dilwyn J.",
    player_two: "Harry, David R",
    g1s: 68,
    g2s: 78,
    g3s: 73,
    g4s: 0,
    g5s: 67,
    g6s: 61,
  },
  {
    player_one: "Davies, Cerith",
    player_two: "Griffiths, Ian H",
    g1s: 68,
    g2s: 0,
    g3s: 66,
    g4s: 66,
    g5s: 66,
    g6s: 0,
  },
  {
    player_one: "Jeffreys, Dave",
    player_two: "Jerimiah, Jay",
    g1s: 69,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Stephens, Chris",
    player_two: "Rees, Wayne",
    g1s: 69,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Jones, Kerry",
    player_two: "Griffiths, Clive",
    g1s: 69,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Ford, Martin",
    player_two: "Trippett, Tom",
    g1s: 70,
    g2s: 76,
    g3s: 0,
    g4s: 69,
    g5s: 71,
    g6s: 0,
  },
  {
    player_one: "Duffy, Roy",
    player_two: "Wootton, David",
    g1s: 72,
    g2s: 0,
    g3s: 0,
    g4s: 64,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Jones, Wayne",
    player_two: "Hughes, Lee",
    g1s: 73,
    g2s: 76,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 81,
  },
  {
    player_one: "Haines, Ian M",
    player_two: "Davies, D Jonathan",
    g1s: 74,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "John, Morgan",
    player_two: "John, Lloyd",
    g1s: 74,
    g2s: 0,
    g3s: 0,
    g4s: 65,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Broad, Nick",
    player_two: "Holmes, Phil",
    g1s: 76,
    g2s: 0,
    g3s: 71,
    g4s: 70,
    g5s: 67,
    g6s: 0,
  },
  {
    player_one: "Wilkins, Bryan",
    player_two: "Manchipp, Clive",
    g1s: 76,
    g2s: 0,
    g3s: 70,
    g4s: 72,
    g5s: 62,
    g6s: 0,
  },
  {
    player_one: "Radford, David",
    player_two: "Hornblower, Rob H.",
    g1s: 0,
    g2s: 62,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Moore, Nick",
    player_two: "Welsh, Simon",
    g1s: 0,
    g2s: 69,
    g3s: 65,
    g4s: 70,
    g5s: 68,
    g6s: 71,
  },
  {
    player_one: "Davies, Cerith",
    player_two: "Grieves, Mike",
    g1s: 0,
    g2s: 71,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "McCalmon, Lester H",
    player_two: "Deak, Michael",
    g1s: 0,
    g2s: 75,
    g3s: 72,
    g4s: 63,
    g5s: 71,
    g6s: 65,
  },
  {
    player_one: "Jones, Alex",
    player_two: "Andrews, Lee",
    g1s: 0,
    g2s: 76,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Binding, Daniel",
    player_two: "Williams, Marc",
    g1s: 64,
    g2s: 64,
    g3s: 64,
    g4s: 0,
    g5s: 0,
    g6s: 69,
  },
  {
    player_one: "Jones, Marc",
    player_two: "Jones, Mason",
    g1s: 0,
    g2s: 0,
    g3s: 65,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Dacey, Kevin",
    player_two: "Veckman, Steve",
    g1s: 0,
    g2s: 0,
    g3s: 67,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Hook, Carl",
    player_two: "Hornblower, Rob H.",
    g1s: 0,
    g2s: 0,
    g3s: 68,
    g4s: 74,
    g5s: 72,
    g6s: 0,
  },
  {
    player_one: "Mears, Sam J",
    player_two: "Griffiths, Clive",
    g1s: 0,
    g2s: 0,
    g3s: 68,
    g4s: 0,
    g5s: 69,
    g6s: 0,
  },
  {
    player_one: "Howard, Matthew",
    player_two: "Carsley, James",
    g1s: 0,
    g2s: 0,
    g3s: 69,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "James, Billy J.",
    player_two: "Ashford, Bryan",
    g1s: 0,
    g2s: 0,
    g3s: 71,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Jerimiah, Jay",
    player_two: "Richards, Craig",
    g1s: 0,
    g2s: 0,
    g3s: 72,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Moore, Paul",
    player_two: "Bray, Gary L",
    g1s: 0,
    g2s: 0,
    g3s: 75,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Stephens, Chris",
    player_two: "Andrews, Lee",
    g1s: 0,
    g2s: 0,
    g3s: 76,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Miles, Mike J",
    player_two: "Rees, Ceri",
    g1s: 0,
    g2s: 0,
    g3s: 91,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Rees, Wayne",
    player_two: "King, William John",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 64,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Williams, Karl",
    player_two: "Mittell, Mathew",
    g1s: 67,
    g2s: 75,
    g3s: 65,
    g4s: 64,
    g5s: 70,
    g6s: 68,
  },
  {
    player_one: "Wilkins, Jonathan J",
    player_two: "Phillipart, Jeff",
    g1s: 0,
    g2s: 0,
    g3s: 77,
    g4s: 65,
    g5s: 64,
    g6s: 0,
  },
  {
    player_one: "Griffiths, Clive",
    player_two: "Brown, William H",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 67,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Gillam, Chris",
    player_two: "Logan, James",
    g1s: 67,
    g2s: 73,
    g3s: 0,
    g4s: 67,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Pitman, John",
    player_two: "Butler, Rob",
    g1s: 0,
    g2s: 71,
    g3s: 0,
    g4s: 73,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "James, Danny",
    player_two: "O'Sullivan, Mark",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 62,
    g6s: 0,
  },
  {
    player_one: "Graham, James",
    player_two: "Brown, William H",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 64,
    g6s: 0,
  },
  {
    player_one: "Moore, Paul",
    player_two: "Howard, Matthew",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 64,
    g6s: 0,
  },
  {
    player_one: "Williams, Marc",
    player_two: "Thomas, Nick",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 66,
    g6s: 0,
  },
  {
    player_one: "Fisher, Karl",
    player_two: "Radford, David",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 66,
    g6s: 0,
  },
  {
    player_one: "Stephens, Chris",
    player_two: "Drewson, Stephen",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 67,
    g6s: 0,
  },
  {
    player_one: "Otten, Marc",
    player_two: "Parton, Wayne",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 70,
    g6s: 0,
  },
  {
    player_one: "Miller, Damien",
    player_two: "Scannell, Ian",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 70,
    g6s: 0,
  },
  {
    player_one: "Jones, Kerry",
    player_two: "Williams, Roger D.",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 63,
  },
  {
    player_one: "Davies, Wayne",
    player_two: "Griffiths, Clive",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 64,
  },
  {
    player_one: "Wilkins, Bryan",
    player_two: "Jerimiah, Jay",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 65,
  },
  {
    player_one: "Bowles, Jeremy",
    player_two: "Stephens, Chris",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 66,
  },
  {
    player_one: "Evans, R. A.",
    player_two: "Bevan, Nigel",
    g1s: 71,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 67,
  },
  {
    player_one: "Miller, Damien",
    player_two: "Parton, Wayne",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 70,
  },
  {
    player_one: "Otten, Marc",
    player_two: "Christensen, Richard",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 70,
  },
  {
    player_one: "Cundy, Leighton",
    player_two: "Cundy, Zach",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 71,
  },
  {
    player_one: "Bromham, Neil",
    player_two: "King, William John",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 71,
  },
];

export function getResultsSummerPairs2025() {
  return result;
}
