const result = [
  {
    player_one: "Davies, Cerith",
    player_two: "Griffiths, Ian H",
    g1s: 63,
    g2s: 72,
    g3s: 65,
    g4s: 63,
    g5s: 65,
    g6s: 0,
  },
  {
    player_one: "Ford, Martin",
    player_two: "Trippett, Tom",
    g1s: 63,
    g2s: 72,
    g3s: 69,
    g4s: 68,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Wood, Karl",
    player_two: "Binding, Daniel",
    g1s: 64,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Linnane, Michael M",
    player_two: "Grieves, Mike",
    g1s: 64,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Logan, James",
    player_two: "Gillam, Chris",
    g1s: 65,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "John, Morgan",
    player_two: "Williams, Steven",
    g1s: 65,
    g2s: 66,
    g3s: 69,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Dacey, Kevin",
    player_two: "Brown, William H",
    g1s: 66,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Duffy, Roy",
    player_two: "Wootton, David",
    g1s: 66,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Jones, Kerry",
    player_two: "Griffiths, Clive",
    g1s: 67,
    g2s: 80,
    g3s: 72,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Lewis, Stephen",
    player_two: "McCalmon, Lester H",
    g1s: 68,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Price, Dilwyn J.",
    player_two: "Harry, David R",
    g1s: 68,
    g2s: 69,
    g3s: 72,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "James, Danny",
    player_two: "O'Sullivan, Mark",
    g1s: 70,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Jerimiah, Jay",
    player_two: "Richards, Craig",
    g1s: 70,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Hughes, Steven",
    player_two: "Cook, Vaughn",
    g1s: 71,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Otten, Marc",
    player_two: "Wheway, Kris",
    g1s: 72,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Hook, Carl",
    player_two: "Hornblower, Rob H.",
    g1s: 73,
    g2s: 0,
    g3s: 69,
    g4s: 71,
    g5s: 62,
    g6s: 0,
  },
  {
    player_one: "Dawe, Nigel F.",
    player_two: "Heycock, Lance L.",
    g1s: 74,
    g2s: 0,
    g3s: 73,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Broad, Nick",
    player_two: "Holmes, Phil",
    g1s: 75,
    g2s: 0,
    g3s: 66,
    g4s: 73,
    g5s: 67,
    g6s: 0,
  },
  {
    player_one: "Hornblower, Rob H.",
    player_two: "Parry, Huw",
    g1s: 0,
    g2s: 65,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Phillipart, Jeff",
    player_two: "Wilkins, Jonathan J",
    g1s: 0,
    g2s: 67,
    g3s: 0,
    g4s: 67,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Mittell, Mathew",
    player_two: "Williams, Karl",
    g1s: 0,
    g2s: 68,
    g3s: 72,
    g4s: 68,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Stephens, Chris",
    player_two: "James, Danny",
    g1s: 0,
    g2s: 68,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Miller, Damien",
    player_two: "Scannell, Ian",
    g1s: 0,
    g2s: 69,
    g3s: 0,
    g4s: 67,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Hughes, Steven",
    player_two: "Jones, Alex",
    g1s: 0,
    g2s: 69,
    g3s: 0,
    g4s: 0,
    g5s: 75,
    g6s: 0,
  },
  {
    player_one: "Williams, Marc",
    player_two: "Taylor, Mark",
    g1s: 68,
    g2s: 70,
    g3s: 70,
    g4s: 63,
    g5s: 66,
    g6s: 0,
  },
  {
    player_one: "Bevan, Nigel",
    player_two: "Drewson, Stephen",
    g1s: 76,
    g2s: 71,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Maimone, Nigel P.",
    player_two: "Barriscale, Phil C.",
    g1s: 68,
    g2s: 73,
    g3s: 69,
    g4s: 72,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Cundy, Leighton",
    player_two: "Cundy, Zach",
    g1s: 67,
    g2s: 73,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Williams, Dafydd",
    player_two: "Lukes, Ben",
    g1s: 0,
    g2s: 75,
    g3s: 75,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Otten, Marc",
    player_two: "Mitchell, Lee",
    g1s: 0,
    g2s: 76,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Davies, Anthony",
    player_two: "Moore, Paul",
    g1s: 0,
    g2s: 77,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Wilkins, Bryan",
    player_two: "Manchipp, Clive",
    g1s: 0,
    g2s: 77,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "James, Billy J.",
    player_two: "Ashford, Bryan",
    g1s: 69,
    g2s: 65,
    g3s: 65,
    g4s: 70,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Jones, Marc",
    player_two: "O'Sullivan, Mark",
    g1s: 0,
    g2s: 0,
    g3s: 66,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Howard, Matthew",
    player_two: "Howard, Nathan",
    g1s: 0,
    g2s: 0,
    g3s: 67,
    g4s: 0,
    g5s: 69,
    g6s: 0,
  },
  {
    player_one: "Fisher, Karl",
    player_two: "Grieves, Mike",
    g1s: 0,
    g2s: 0,
    g3s: 69,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Miles, Mike J",
    player_two: "Rees, Jac K",
    g1s: 0,
    g2s: 0,
    g3s: 69,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Wilkins, Jonathan J",
    player_two: "Radford, David",
    g1s: 0,
    g2s: 0,
    g3s: 72,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Hughes, Steven",
    player_two: "Webb, Cameron",
    g1s: 0,
    g2s: 0,
    g3s: 73,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Butler, Rob",
    player_two: "Pitman, John",
    g1s: 68,
    g2s: 0,
    g3s: 75,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Quinn, Paul",
    player_two: "Manchipp, Clive",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 64,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Moore, Nick",
    player_two: "Welsh, Simon",
    g1s: 64,
    g2s: 63,
    g3s: 70,
    g4s: 65,
    g5s: 67,
    g6s: 0,
  },
  {
    player_one: "Rees, Wayne",
    player_two: "Stephens, Chris",
    g1s: 67,
    g2s: 0,
    g3s: 68,
    g4s: 67,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Otten, Marc",
    player_two: "Cundy, Leighton",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 67,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Hughes, Lee",
    player_two: "Moore, Paul",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 67,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Jones, Kerry",
    player_two: "Dacey, Kevin",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 67,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Miles, Mike J",
    player_two: "Bowles, Jeremy",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 68,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Cook, Vaughn",
    player_two: "Bevan, Nigel",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 69,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Howard, Matthew",
    player_two: "Carsley, Kevin",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 71,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "King, William John",
    player_two: "Bromham, Neil",
    g1s: 64,
    g2s: 0,
    g3s: 69,
    g4s: 72,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Andrews, Lee",
    player_two: "Webb, Cameron",
    g1s: 61,
    g2s: 0,
    g3s: 0,
    g4s: 82,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Jones, Wayne",
    player_two: "Hughes, Lee",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 62,
    g6s: 0,
  },
  {
    player_one: "Hills, Dean S",
    player_two: "Bromham, Derek J",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 66,
    g6s: 0,
  },
  {
    player_one: "Wood, Karl",
    player_two: "Davies, Anthony",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 68,
    g6s: 0,
  },
  {
    player_one: "Wilkins, Bryan",
    player_two: "McCalmon, Lester H",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 68,
    g6s: 0,
  },
  {
    player_one: "McLean, Neil",
    player_two: "Jones, D. Roy",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 73,
    g6s: 0,
  },
  {
    player_one: "Jerimiah, Jay",
    player_two: "Bray, Gary L",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 73,
    g6s: 0,
  },
];

export function getResultsSummerPairs2026() {
  return result;
}
