const result = [
  {
    player_one: "Fisher, Karl",
    player_two: "Flack, Gary",
    g1s: 44,
    g2s: 45,
    g3s: 0,
    g4s: 0,
    g5s: 39,
    g6s: 46,
  },
  {
    player_one: "Broad, Nick",
    player_two: "Holmes, Phil",
    g1s: 43,
    g2s: 0,
    g3s: 43,
    g4s: 0,
    g5s: 38,
    g6s: 37,
  },
  {
    player_one: "Wilkins, Bryan",
    player_two: "Manchipp, Clive",
    g1s: 43,
    g2s: 0,
    g3s: 36,
    g4s: 36,
    g5s: 38,
    g6s: 39,
  },
  {
    player_one: "Linnane, Michael M",
    player_two: "Grieves, Mike",
    g1s: 42,
    g2s: 41,
    g3s: 0,
    g4s: 37,
    g5s: 40,
    g6s: 40,
  },
  {
    player_one: "Hook, Carl",
    player_two: "Hornblower, Rob H.",
    g1s: 42,
    g2s: 49,
    g3s: 0,
    g4s: 41,
    g5s: 40,
    g6s: 41,
  },
  {
    player_one: "Williams, Marc",
    player_two: "Jerimiah, Jay",
    g1s: 40,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 39,
  },
  {
    player_one: "Jones, Marc",
    player_two: "O'Sullivan, Mark",
    g1s: 40,
    g2s: 41,
    g3s: 44,
    g4s: 33,
    g5s: 35,
    g6s: 0,
  },
  {
    player_one: "Wilkins, Jonathan J",
    player_two: "Bugden, Mike",
    g1s: 39,
    g2s: 40,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Maimone, Nigel P.",
    player_two: "Barriscale, Phil C.",
    g1s: 36,
    g2s: 38,
    g3s: 38,
    g4s: 0,
    g5s: 41,
    g6s: 35,
  },
  {
    player_one: "Hughes, Steven",
    player_two: "Webb, Cameron",
    g1s: 36,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Williams, Dafydd",
    player_two: "John, Morgan",
    g1s: 35,
    g2s: 34,
    g3s: 39,
    g4s: 39,
    g5s: 0,
    g6s: 38,
  },
  {
    player_one: "McCalmon, Lester H",
    player_two: "Deak, Michael",
    g1s: 0,
    g2s: 42,
    g3s: 38,
    g4s: 36,
    g5s: 34,
    g6s: 36,
  },
  {
    player_one: "Williams, Marc",
    player_two: "Howard, Matthew",
    g1s: 0,
    g2s: 41,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "McLean, Neil",
    player_two: "Jones, D. Roy",
    g1s: 0,
    g2s: 40,
    g3s: 0,
    g4s: 41,
    g5s: 40,
    g6s: 40,
  },
  {
    player_one: "Palmer, Colin",
    player_two: "Drewson, Stephen",
    g1s: 40,
    g2s: 39,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Wood, Karl",
    player_two: "Davies, Anthony",
    g1s: 0,
    g2s: 39,
    g3s: 38,
    g4s: 0,
    g5s: 43,
    g6s: 0,
  },
  {
    player_one: "Parton, Wayne",
    player_two: "Phippen, Brett",
    g1s: 34,
    g2s: 38,
    g3s: 33,
    g4s: 35,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Manchipp, Clive",
    player_two: "Moore, Paul",
    g1s: 0,
    g2s: 38,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Bromham, Derek J",
    player_two: "King, William John",
    g1s: 43,
    g2s: 37,
    g3s: 33,
    g4s: 36,
    g5s: 35,
    g6s: 0,
  },
  {
    player_one: "Mittell, Mathew",
    player_two: "Harry, David R",
    g1s: 0,
    g2s: 36,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Davies, Cerith",
    player_two: "Radford, David",
    g1s: 0,
    g2s: 35,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Broad, Nick",
    player_two: "Taylor, Mark",
    g1s: 0,
    g2s: 35,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Price, Dilwyn J.",
    player_two: "Harry, David R",
    g1s: 0,
    g2s: 0,
    g3s: 44,
    g4s: 37,
    g5s: 39,
    g6s: 41,
  },
  {
    player_one: "Miles, Mike J",
    player_two: "Rees, Jac K",
    g1s: 0,
    g2s: 0,
    g3s: 44,
    g4s: 34,
    g5s: 35,
    g6s: 0,
  },
  {
    player_one: "Williams, Gareth",
    player_two: "Lowe, Gary",
    g1s: 0,
    g2s: 37,
    g3s: 41,
    g4s: 39,
    g5s: 36,
    g6s: 0,
  },
  {
    player_one: "Ashford, Bryan",
    player_two: "James, Billy J.",
    g1s: 36,
    g2s: 43,
    g3s: 41,
    g4s: 40,
    g5s: 0,
    g6s: 34,
  },
  {
    player_one: "Jeffreys, Dave",
    player_two: "Richards, Craig",
    g1s: 0,
    g2s: 0,
    g3s: 40,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Quinn, Paul",
    player_two: "Pitman, John",
    g1s: 0,
    g2s: 0,
    g3s: 39,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "James, Danny",
    player_two: "Jones, D. Roy",
    g1s: 0,
    g2s: 0,
    g3s: 38,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Howard, Matthew",
    player_two: "Moore, Paul",
    g1s: 0,
    g2s: 0,
    g3s: 38,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Stephens, Chris",
    player_two: "Rees, Wayne",
    g1s: 35,
    g2s: 0,
    g3s: 37,
    g4s: 29,
    g5s: 38,
    g6s: 39,
  },
  {
    player_one: "Bowles, Jeremy",
    player_two: "Rees, Ceri",
    g1s: 0,
    g2s: 0,
    g3s: 35,
    g4s: 0,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Scannell, Ian",
    player_two: "Miller, Damien",
    g1s: 30,
    g2s: 41,
    g3s: 35,
    g4s: 32,
    g5s: 40,
    g6s: 39,
  },
  {
    player_one: "Bowles, Jeremy",
    player_two: "Morris, Dean",
    g1s: 36,
    g2s: 40,
    g3s: 0,
    g4s: 44,
    g5s: 43,
    g6s: 0,
  },
  {
    player_one: "Ford, Martin",
    player_two: "Trippett, Tom",
    g1s: 39,
    g2s: 39,
    g3s: 38,
    g4s: 38,
    g5s: 44,
    g6s: 39,
  },
  {
    player_one: "Phillipart, Jeff",
    player_two: "Wilkins, Jonathan J",
    g1s: 0,
    g2s: 0,
    g3s: 38,
    g4s: 38,
    g5s: 41,
    g6s: 42,
  },
  {
    player_one: "Graham, James",
    player_two: "Mittell, Mathew",
    g1s: 33,
    g2s: 0,
    g3s: 42,
    g4s: 38,
    g5s: 11,
    g6s: 0,
  },
  {
    player_one: "Moore, Nick",
    player_two: "Moore, Paul",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 38,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Bakali, Abdul Adam",
    player_two: "Bray, Gary L",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 38,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Williams, Karl",
    player_two: "Williams, Mike",
    g1s: 0,
    g2s: 45,
    g3s: 40,
    g4s: 36,
    g5s: 32,
    g6s: 40,
  },
  {
    player_one: "Binding, Daniel",
    player_two: "Williams, Marc",
    g1s: 0,
    g2s: 0,
    g3s: 39,
    g4s: 36,
    g5s: 41,
    g6s: 0,
  },
  {
    player_one: "Broad, Nick",
    player_two: "Howard, Nathan",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 36,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Griffiths, Clive",
    player_two: "Jones, Kerry",
    g1s: 44,
    g2s: 44,
    g3s: 39,
    g4s: 36,
    g5s: 41,
    g6s: 37,
  },
  {
    player_one: "Dacey, Kevin",
    player_two: "Barriscale, Phil C.",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 35,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Jeffreys, Dave",
    player_two: "Jones, Wayne",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 35,
    g5s: 0,
    g6s: 0,
  },
  {
    player_one: "Watkins, Steve",
    player_two: "Moule, Glanville D",
    g1s: 40,
    g2s: 40,
    g3s: 38,
    g4s: 31,
    g5s: 35,
    g6s: 32,
  },
  {
    player_one: "Welsh, Simon",
    player_two: "Moore, Nick",
    g1s: 39,
    g2s: 37,
    g3s: 40,
    g4s: 0,
    g5s: 37,
    g6s: 43,
  },
  {
    player_one: "Palmer, Colin",
    player_two: "Schofield, Paul",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 35,
    g6s: 0,
  },
  {
    player_one: "Griffiths, Ian H",
    player_two: "Davies, Cerith",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 34,
    g6s: 35,
  },
  {
    player_one: "Miller, Ian",
    player_two: "James, Danny",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 45,
  },
  {
    player_one: "Howard, Matthew",
    player_two: "Carsley, Kevin",
    g1s: 33,
    g2s: 0,
    g3s: 0,
    g4s: 39,
    g5s: 0,
    g6s: 41,
  },
  {
    player_one: "Haines, Ian M",
    player_two: "Bakali, Abdul Adam",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 39,
  },
  {
    player_one: "Mittell, Mathew",
    player_two: "Bevan, Nigel",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 38,
  },
  {
    player_one: "Andrews, Lee",
    player_two: "Jones, Alex",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 38,
  },
  {
    player_one: "Cundy, Leighton",
    player_two: "Cundy, Zach",
    g1s: 35,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 35,
  },
  {
    player_one: "Wheway, Kris",
    player_two: "O'Mahoney, Richard",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 33,
  },
  {
    player_one: "Bevan, Leigh",
    player_two: "Bevan, Tim",
    g1s: 0,
    g2s: 0,
    g3s: 0,
    g4s: 0,
    g5s: 0,
    g6s: 25,
  },
];

export function getResultsWinterPairs2025() {
  return result;
}
